name: Build and push Docker images

on:
  release:
    types: [published]

# for debugging
# on:
#   push

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Extract Branch/Tag Names
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push(Bullseye)
        uses: docker/build-push-action@v3.2.0
        with:
          context: bullseye/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/redpen:bullseye-latest,${{ secrets.DOCKERHUB_USERNAME }}/redpen:latest,${{ secrets.DOCKERHUB_USERNAME }}/redpen:bullseye-${{ env.TAG }},${{ secrets.DOCKERHUB_USERNAME }}/redpen:${{ env.TAG }}
          cache-to: type=gha,mode=max
          cache-from: type=gha
      -
        name: Build and push(Buster)
        uses: docker/build-push-action@v3.2.0
        with:
          context: buster/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/redpen:buster-latest,${{ secrets.DOCKERHUB_USERNAME }}/redpen:buster-${{ env.TAG }}
          cache-to: type=gha,mode=max
          cache-from: type=gha
